import { ClubPosition, IMember } from "@/members/models";

export const pgFall23: IMember[] = [
  {
    name: "Patrick Fisher",
    photoPath: "/pg/fall23/patrick.jpg",
    position: ClubPosition.president,
    socials: {},
    isPg: true,
    isBoard: true,
    hometown: "San Francisco, California",
    astrologicalSign: "Taurus",
    description:
      "I started improv my freshman year of highschool. My sister and her friends brought me to the improv club and I was in love instantly.",
  },
  {
    name: "Liz Wigington",
    photoPath: "/pg/fall23/liz.webp",
    position: ClubPosition.artisticDirector,
    socials: {},
    isPg: true,
    isBoard: true,
    hometown: "Las Vegas, Nevada",
    astrologicalSign: "Aries",
    description:
      "I started doing improv the fall semester of my sophomore year in college with the improv stuco!",
  },
  {
    name: "Jett Hays",
    photoPath: "/pg/fall23/jett.webp",
    position: ClubPosition.troupeManager,
    socials: {},
    isPg: true,
    isBoard: true,
    hometown: "Torrance, California",
    astrologicalSign: "Gemini",
    description:
      "Improv is a lightning ⚡️ bolt of energy and laughter. I was struck on my first day of college, and I haven’t recovered.  And the people... oh my gosh, the people!",
  },
  {
    name: "Alex Newkirk",
    photoPath: "/pg/fall23/alex.webp",
    position: ClubPosition.detourChair,
    socials: {},
    isPg: true,
    isBoard: true,
    hometown: "Clarendon Hills, Illinois",
    astrologicalSign: "Gemini",
    description:
      "I began 14 years ago as of May 2023. I trained in Chicago, performed in Illinois, Minneapolis, the Bay area, and Pittsburgh.",
  },
  {
    name: "Arrim Jung",
    photoPath: "/pg/fall23/arrim.webp",
    position: ClubPosition.social,
    socials: {},
    isPg: true,
    isBoard: true,
    hometown: "Seoul, South Korea",
    astrologicalSign: "Gasp!",
    description:
      "How I met improv? Gosh, let me see... it was Fall of 2022 when Call Your Ma (the annual subtroupe collab show) auditions opened. I marked that I was willing to do both acting and improv and had no idea what I was getting into. But in the audition room, improv and I just locked eyes (Stoppp I'm not blushing!). \n I was fumbling, no idea what was coming out of my mouth, but improv listened to my ideas patiently and inspired me to push my limits. When I performed with the rest of cast, improv held my hand and gave me courage. \n I looked for ways to get to know him better and started to go to Workshops. There were some embarrassing moments, but hey, we were embarrassing together. \n I took a chance by auditioning for NPP troupe, and improv took a chance on me. And we've been happy together ever since",
  },
  {
    name: "Stephen Tao",
    photoPath: "/pg/fall23/stephen.jpg",
    position: ClubPosition.detourChair,
    socials: {},
    isPg: true,
    isBoard: true,
    hometown: "San Jose, California",
    astrologicalSign: "Leo",
    description:
      "It was a silly goofy thing I did in high school that I wanted to do at CMU !!!",
  },
  {
    name: "Efe Cekirge",
    photoPath: "/pg/fall23/efe.webp",
    position: ClubPosition.pg,
    socials: {},
    isPg: true,
    isBoard: false,
    astrologicalSign: "Taurus",
    hometown: "İstanbul, Türkiye",
    description:
      "In my senior year of high school, I learned about improv by watching Whose Line clips. Then, when I came to CMU, NPP had a performance in our orientation week, and I was hooked.",
  },
  {
    name: "Peter Ragone",
    photoPath: "/pg/fall23/peter.webp",
    position: ClubPosition.pg,
    socials: {},
    isPg: true,
    isBoard: false,
    hometown: "Boston, Massachusetts",
  },
  {
    name: "Gabriel Aguirre",
    photoPath: "/pg/fall23/gabe.jpg",
    position: ClubPosition.pg,
    socials: {},
    isPg: true,
    isBoard: false,
    astrologicalSign: "Sagittarius",
    hometown: "Lexington, Massachusetts",
    description:
      "I had hopes of hosting a late night show as a kid and this is how I cling onto that fading dream.",
  },
  {
    name: "Kaya Kozlowski",
    photoPath: "/pg/fall23/kaya.jpg",
    position: ClubPosition.pg,
    socials: {},
    isPg: true,
    isBoard: false,
    astrologicalSign: "Aquarius",
    hometown: "Schiller Park, Illinois",
    description:
      "I like being silly and doing silly things!!!! I also like laughing!!!! And I like making other people laugh!!!!!!!!",
  },
];
