import { ClubPosition, IMember } from "@/members/models";

export const pgSpring23: IMember[] = [
  {
    name: "Julia Loghinov",
    photoPath: "/pg/spring23/julia.webp",
    position: ClubPosition.president,
    socials: {},
    isPg: true,
    isBoard: true,
  },
  {
    name: "Efe Cekirge",
    photoPath: "/pg/spring23/efe.webp",
    position: ClubPosition.artisticDirector,
    socials: {},
    isPg: true,
    isBoard: true,
  },
  {
    name: "Gavin Grnja",
    photoPath: "/pg/spring23/gavin.webp",
    position: ClubPosition.social,
    socials: {},
    isPg: true,
    isBoard: true,
  },
  {
    name: "Liz Wigington",
    photoPath: "/pg/spring23/liz.webp",
    position: ClubPosition.troupeManager,
    socials: {},
    isPg: true,
    isBoard: true,
  },
  {
    name: "Stephen Tao",
    photoPath: "/pg/spring23/stephen.jpg",
    position: ClubPosition.pg,
    socials: {},
    isPg: true,
    isBoard: false,
  },
  {
    name: "Patrick Fisher",
    photoPath: "/pg/spring23/patrick.jpg",
    position: ClubPosition.pg,
    socials: {},
    isPg: true,
    isBoard: false,
  },
  {
    name: "Jett Hays",
    photoPath: "/pg/spring23/jett.webp",
    position: ClubPosition.pg,
    socials: {},
    isPg: true,
    isBoard: false,
  },
  {
    name: "Peter Ragone",
    photoPath: "/pg/spring23/peter.webp",
    position: ClubPosition.pg,
    socials: {},
    isPg: true,
    isBoard: false,
  },
  {
    name: "Alex Newkirk",
    photoPath: "/pg/spring23/alex.webp",
    position: ClubPosition.pg,
    socials: {},
    isPg: true,
    isBoard: false,
  },
  {
    name: "Arrim Jung",
    photoPath: "/pg/spring23/arrim.webp",
    position: ClubPosition.pg,
    socials: {},
    isPg: true,
    isBoard: false,
  },
];
